jotun/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from tsnumber import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles

urlpatterns = [
    path('admin/', admin.site.urls),
    # url('^(\d+)/$',views.tsview,name='index1'),
    url('^$',views.index,name='index'),
    url('^tsinfo/',include(('tsnumber.urls','tsnumber'),namespace='tsinfo')),
    url('^upfiles/$',views.upfiles),
    url('^savefile/$',views.savefile),
]
urlpatterns += staticfiles_urlpatterns()

tsnumber/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from tsnumber import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles

urlpatterns = [
    url('^search/(\d+)/$',views.searchpage,name='searchpage'),
    url('^search/$',views.search,name='search'),
    url('^login/$',views.login,name='login'),
    url('^quit/$',views.quit,name='quit'),
    url('^verify/$',views.verifycode,name='verify'),
    # url('^main/$',views.main,name='main')
]
urlpatterns += staticfiles_urlpatterns()

templates/jotun/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static "tsnumber/css/soutu.css" %}">
    <title></title>
{#    <style>#}
{#        #header{#}
{#            width: 100%;#}
{#            height:100px;#}
{#            background-color: #8e8e8e;#}
{##}
{#        }#}
{#    </style>#}
</head>
<body>
    <div id="header">Jotun TS人员信息查询系统</div>
    <div id="main">
        {% block main %}
        {% endblock %}
    </div>
    <hr>
    <div id="footer" >中远佐敦船舶涂料青岛有限公司 by:何丹</div>
{#    <img src="{% static "tsnumber/jpg/user_right.jpg" %}">#}
</body>
</html>

templates/jotun/index.html
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static "tsnumber/css/style.css" %}">
    <title>Jotun TSS查询系统！</title>
    

</head>
<body>
    {% comment %}
    {% if username  %}
        <h2>你输入的“{{ username }}”在数据库中不存在或者验证码输入错误，请正确输入！</h2>
    {% else %}
        <h2>请输入你的姓名后查询系统！</h2>
    {% endif %}
    {% endcomment %}
    <h2>Jotun TSS查询系统登录</h2>
    <form action="{% url "tsinfo:login" %}" method="post">
        {% csrf_token %}
        验证码：<input type="text" name="verify">
        <img src="{% url "tsinfo:verify" %}">
        用户名：<input type="text" name="username">
        <input type="submit" value="提交">
    </form>
    <span>{{ flag }}</span>
    <img src="{% static "tsnumber/jpg/3.jpg" %}">
</body>
</html>

templates/jotun/index1.html
{% extends "jotun/base.html" %}
{% block main %}
<h2>Jotun TSS查询系统登录</h2>
    <table>
    <tr>
        <td><form action="{% url "tsinfo:login" %}" method="post">
        {% csrf_token %}
        验证码：<input type="text" name="verify">
        <img src="{% url "tsinfo:verify" %}">
        用户名：<input type="text" name="username">
        <input type="submit" value="提交">
    </form>
        </td>
    </tr>
    <tr>
        <td>
            <span>{{ flag }}</span>
        </td>
    </tr>
    </table>


{% endblock %}

templates/jotun/page.html
{% extends "jotun/base.html" %}
{% block main %}
{#    <h1>Jotun TSS信息列表</h1>#}
    <h2>欢迎:{{ username }}  </h2>
    <a id="a"> 登录 </a>
    <a id="a" href="{% url "tsinfo:quit" %}">退出 </a>
    <table>
        <tr>
            <td>
                <form action="{% url 'tsinfo:search' %}" method="post">
                    {% csrf_token %}
                       关键词：<input type="text" name="keyword" value="{{ keyword}}">
                        <input type="submit" value="查询">
{#                        <hr>#}
                </form>
            </td>
        </tr>
        <tr>
            <td>
                <a id="a_small">（显示全部请在关键字一栏输入一个空格键或者数字1！）</a>
                <hr>
            </td>
        </tr>       
        {% if error_msg %}
        <tr>
        <td>
        {{error_msg}}
        </td>
        </tr>
        {%endif%}
        
        

    </table>
<ul>
            
         <table id="details">
                <tr id="tr-title">
                    <td>序号</td>
                    <td>姓名</td>
                    <td>船厂</td>
                    <td>邮箱</td>
                    <td>联系电话</td>
                </tr>
            {% for student in students %}
                    {%widthratio students.number 1 10 as pagenum%}
                    <tr id="tr-detail">
                        <td>{{ forloop.counter|add:pagenum|add:-10 }}</td>
                        <td>{{ student.chinname }}</td>
                        <td>{{ student.shipyard }}</td>
                        <td>{{ student.email }}</td>
                        <td>{{ student.tel }}</td>
                    </tr>
            {% empty %}
                  <div id="no-answer">
                    没有搜索结果
                  </div>
            {% endfor %}

         </table>
    <table>
        <tr>
            {% if students.has_previous %}
                <td><a href="/tsinfo/search/{{students.previous_page_number}}">上一页</a></td>
            {% else %}
                <td><a>上一页</a></td>
            {% endif %}
            {% for index in students.paginator.page_range %}
                {% if index == students.number %}
                    <td>{{ index }}</td>
                {% else %}
                    <td><a href="/tsinfo/search/{{index}}">{{ index }}</a></td>
                {% endif %}
            {%endfor%}
            {% if students.has_next %}
                <td><a href="/tsinfo/search/{{students.next_page_number}}">下一页</a></td>
            {% else %}
                <td><a>下一页</a></td>
            {% endif %}
        </tr>
    </table>
</ul>
{% endblock %}

templates/jotun/tss.html
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static "tsnumber/css/style.css" %}">
    <title>Jotun TSS信息列表</title>
</head>
<body>
    <h1>Jotun TSS信息列表</h1>
    <h2>欢迎:{{ username }}</h2>
    <a> 登录</a>
    <a href="{% url "tsinfo:quit" %}">退出</a>
    <form action="{% url 'tsinfo:search' %}" method="post">
        {% csrf_token %}
           关键词：<input type="text" name="keyword" value="{{ keyword}}">
            <input type="submit" value="查询">
            <hr>
    </form>
    <ul>
        {% if error_msg %}
            <p>{{ error_msg }}</p>
        {% endif %}
         <table class="table-bordered">
                <tr>
                    <td>序号</td>
                    <td>姓名</td>
                    <td>船厂</td>
                    <td>邮箱</td>
                    <td>联系电话</td>
                </tr>
            {% for student in students %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ student.chinname }}</td>
                        <td>{{ student.shipyard }}</td>
                        <td>{{ student.email }}</td>
                        <td>{{ student.tel }}</td>
                    </tr>
            {% empty %}
                  <div >
                    没有搜索结果
                  </div>
            {% endfor %}
         </table>
    </ul>
</body>
</html>

templates/jotun/tssearch.html
{% extends "jotun/base.html" %}
{% block main %}
{#    <h1>Jotun TSS信息列表</h1>#}
    <h2>欢迎:{{ username }}  </h2>
    <a id="a"> 登录 </a>
    <a id="a" href="{% url "tsinfo:quit" %}">退出 </a>
    <form action="{% url 'tsinfo:search' %}" method="post">
        {% csrf_token %}
           关键词：<input type="text" name="keyword" value="{{ keyword}}">
            <input type="submit" value="查询">
            <hr>
    </form>
<ul>
        {% if error_msg %}
            <p>{{ error_msg }}</p>
        {% endif %}
         <table id="details">
                <tr id="tr-title">
                    <td>序号</td>
                    <td>姓名</td>
                    <td>船厂</td>
                    <td>邮箱</td>
                    <td>联系电话</td>
                </tr>
            {% for student in students %}
                    <tr id="tr-detail">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ student.chinname }}</td>
                        <td>{{ student.shipyard }}</td>
                        <td>{{ student.email }}</td>
                        <td>{{ student.tel }}</td>
                    </tr>
            {% empty %}
                  <div id="no-answer">
                    没有搜索结果
                  </div>
            {% endfor %}

         </table>
    <table>
        <tr>
            {% for index in students.paginator.page_range %}
                {% if index == students.number %}
                    <td>{{ index }}</td>
                {% else %}
                    <td><a href="/tsinfo/search/{{index}}">{{ index }}</a></td>
                {% endif %}
            {%endfor%}
            <td><a href="/tsinfo/search/{{pageid|add:1}}">下一页</a></td>
        </tr>
    </table>
</ul>
{% endblock %}

templates/jotun/uploads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文件上传</title>
</head>
<body>
<form action="/savefile/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file">
    <input type="submit",value="上传">
</form>
</body>
</html>